name: test

on:
  push:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.16.15"
          cache: true
      - run: go test -cover -v ./...
      - uses: golangci/golangci-lint-action@v3
